name: Build k0sctl AUR Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        run: |
          output_dir="$PWD/packages"
          mkdir -p "$output_dir"
          chmod +w "$output_dir"
          docker run --rm --pull always -v "$output_dir:/packages" ghcr.io/pschichtel/makepkg:v12 yay -S --noconfirm k0sctl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./packages
