name: Build k0sctl AUR Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set matrix data
       id: set-matrix
       run: |
         which yq
         yq --help
         echo "matrix=$(yq eval -o json '.' packages.yaml | jq -cM '.include = (.packages | map({name: .})) | del(.packages)')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package ${{ matrix.name }}
        run: |
          output_dir="$PWD/packages"
          mkdir -p "$output_dir"
          chmod +w "$output_dir"
          podman run --userns="keep-id:uid=1000" --rm --pull always -v "$output_dir:/packages" ghcr.io/pschichtel/makepkg:v12 yay -S --noconfirm "${{ matrix.name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.name }}
          path: ./packages

  create-repo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./repo-packages

      - name: Create repository
        run: |
          find ./repo-packages
          repo_dir="$PWD/repo-packages"
          podman run --userns="keep-id:uid=1000" --rm --pull always -v "$repo_dir:/repo-packages" ghcr.io/pschichtel/makepkg:v12 repo-add /repo-packages/pschichtel.db.tar.gz /repo-packages/*.pkg.tar.zst

      - name: Upload repository artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: ./repo-packages

