name: Build k0sctl AUR Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build k0sctl package
        run: |
          mkdir -o packages
          docker run --rm -it -v "$PWD/packages:/packages" yay -S --noconfirm k0sctl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k0sctl-package
          path: ./packages
